<%@ Control Language="C#" AutoEventWireup="true" CodeBehind="Proofing.ascx.cs" Inherits="testing.Proofing" %>
<div class="container">
    <input type="text" id="projectname" title="projectname" />
    <input type="text" id="jobid" title="jobid" />
    <input type="text" id="jobName" title="jobName" />
    <input type="button" id="btnGenerate" value="Generate Proof" />
    <input type="hidden" id="displayname" />
    <ul id="proofMessages"></ul>
</div>
    <!--Script references. -->
    <!--Reference the jQuery library. -->
    <script src="Scripts/jquery-3.1.1.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Add script to update the page and send messages.-->
    <script type="text/javascript">
        $(function () {
            // Declare a proxy to reference the hub.
            var chat = $.connection.proofHub;
            var file = $.connection.fileHub;
            // Create a function that the hub can call to broadcast messages.
            chat.client.proofMessage = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#proofMessages').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            chat.client.writeFile = function (name, message) {
                // Html encode display name and message.
                var encodedName = $('<div />').text(name).html();
                var encodedMsg = $('<div />').text(message).html();
                // Add the message to the page.
                $('#proofMessages').append('<li><strong>' + encodedName
                    + '</strong>:&nbsp;&nbsp;' + encodedMsg + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            $('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            $('#message').focus();
            //Set the querystring
            $.connection.hub.qs = { 'name' : $('#displayname').val() }
            // Start the connection.
            $.connection.hub.start().done(function () {
                $('#btnGenerate').click(function () {
                    chat.server.generateProof($('#projectname').val(), $('#jobid').val(), $('#jobName').val());
                });
            });
        });

    </script>