//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testing.Verivdp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="returnType", Namespace="http://schemas.datacontract.org/2004/07/VeriVDP")]
    [System.SerializableAttribute()]
    public partial class returnType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommandPacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionDetails {
            get {
                return this.ActionDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionDetailsField, value) != true)) {
                    this.ActionDetailsField = value;
                    this.RaisePropertyChanged("ActionDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionStatus {
            get {
                return this.ActionStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionStatusField, value) != true)) {
                    this.ActionStatusField = value;
                    this.RaisePropertyChanged("ActionStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommandPacket {
            get {
                return this.CommandPacketField;
            }
            set {
                if ((object.ReferenceEquals(this.CommandPacketField, value) != true)) {
                    this.CommandPacketField = value;
                    this.RaisePropertyChanged("CommandPacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="requestType", Namespace="http://schemas.datacontract.org/2004/07/VeriVDP")]
    [System.SerializableAttribute()]
    public partial class requestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBConnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionValue {
            get {
                return this.ActionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionValueField, value) != true)) {
                    this.ActionValueField = value;
                    this.RaisePropertyChanged("ActionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetStatus {
            get {
                return this.AssetStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetStatusField, value) != true)) {
                    this.AssetStatusField = value;
                    this.RaisePropertyChanged("AssetStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetTemplate {
            get {
                return this.AssetTemplateField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTemplateField, value) != true)) {
                    this.AssetTemplateField = value;
                    this.RaisePropertyChanged("AssetTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetText {
            get {
                return this.AssetTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTextField, value) != true)) {
                    this.AssetTextField = value;
                    this.RaisePropertyChanged("AssetText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssetType {
            get {
                return this.AssetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssetTypeField, value) != true)) {
                    this.AssetTypeField = value;
                    this.RaisePropertyChanged("AssetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBConn {
            get {
                return this.DBConnField;
            }
            set {
                if ((object.ReferenceEquals(this.DBConnField, value) != true)) {
                    this.DBConnField = value;
                    this.RaisePropertyChanged("DBConn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Programid {
            get {
                return this.ProgramidField;
            }
            set {
                if ((this.ProgramidField.Equals(value) != true)) {
                    this.ProgramidField = value;
                    this.RaisePropertyChanged("Programid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="requestTypeObject", Namespace="http://schemas.datacontract.org/2004/07/VeriVDP")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(testing.Verivdp.requestTypeXmPie))]
    public partial class requestTypeObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPreviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool JobMonitorEnabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QueueNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SplittingCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SplittingTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SqlstatementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string commandpacketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string environmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isProofField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> jobvariablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int recipientCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionValue {
            get {
                return this.ActionValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionValueField, value) != true)) {
                    this.ActionValueField = value;
                    this.RaisePropertyChanged("ActionValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPreview {
            get {
                return this.IsPreviewField;
            }
            set {
                if ((this.IsPreviewField.Equals(value) != true)) {
                    this.IsPreviewField = value;
                    this.RaisePropertyChanged("IsPreview");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool JobMonitorEnabled {
            get {
                return this.JobMonitorEnabledField;
            }
            set {
                if ((this.JobMonitorEnabledField.Equals(value) != true)) {
                    this.JobMonitorEnabledField = value;
                    this.RaisePropertyChanged("JobMonitorEnabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobName {
            get {
                return this.JobNameField;
            }
            set {
                if ((object.ReferenceEquals(this.JobNameField, value) != true)) {
                    this.JobNameField = value;
                    this.RaisePropertyChanged("JobName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jobid {
            get {
                return this.JobidField;
            }
            set {
                if ((object.ReferenceEquals(this.JobidField, value) != true)) {
                    this.JobidField = value;
                    this.RaisePropertyChanged("Jobid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputPath {
            get {
                return this.OutputPathField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputPathField, value) != true)) {
                    this.OutputPathField = value;
                    this.RaisePropertyChanged("OutputPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Programid {
            get {
                return this.ProgramidField;
            }
            set {
                if ((this.ProgramidField.Equals(value) != true)) {
                    this.ProgramidField = value;
                    this.RaisePropertyChanged("Programid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QueueName {
            get {
                return this.QueueNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QueueNameField, value) != true)) {
                    this.QueueNameField = value;
                    this.RaisePropertyChanged("QueueName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SplittingCount {
            get {
                return this.SplittingCountField;
            }
            set {
                if ((this.SplittingCountField.Equals(value) != true)) {
                    this.SplittingCountField = value;
                    this.RaisePropertyChanged("SplittingCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SplittingType {
            get {
                return this.SplittingTypeField;
            }
            set {
                if ((this.SplittingTypeField.Equals(value) != true)) {
                    this.SplittingTypeField = value;
                    this.RaisePropertyChanged("SplittingType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sqlstatement {
            get {
                return this.SqlstatementField;
            }
            set {
                if ((object.ReferenceEquals(this.SqlstatementField, value) != true)) {
                    this.SqlstatementField = value;
                    this.RaisePropertyChanged("Sqlstatement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string commandpacket {
            get {
                return this.commandpacketField;
            }
            set {
                if ((object.ReferenceEquals(this.commandpacketField, value) != true)) {
                    this.commandpacketField = value;
                    this.RaisePropertyChanged("commandpacket");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string environment {
            get {
                return this.environmentField;
            }
            set {
                if ((object.ReferenceEquals(this.environmentField, value) != true)) {
                    this.environmentField = value;
                    this.RaisePropertyChanged("environment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((object.ReferenceEquals(this.filenameField, value) != true)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isProof {
            get {
                return this.isProofField;
            }
            set {
                if ((this.isProofField.Equals(value) != true)) {
                    this.isProofField = value;
                    this.RaisePropertyChanged("isProof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> jobvariables {
            get {
                return this.jobvariablesField;
            }
            set {
                if ((object.ReferenceEquals(this.jobvariablesField, value) != true)) {
                    this.jobvariablesField = value;
                    this.RaisePropertyChanged("jobvariables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recipientCount {
            get {
                return this.recipientCountField;
            }
            set {
                if ((this.recipientCountField.Equals(value) != true)) {
                    this.recipientCountField = value;
                    this.RaisePropertyChanged("recipientCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="requestTypeXmPie", Namespace="http://schemas.datacontract.org/2004/07/VeriVDP")]
    [System.SerializableAttribute()]
    public partial class requestTypeXmPie : testing.Verivdp.requestTypeObject {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Verivdp.IVeriVDP")]
    public interface IVeriVDP {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetPageCounts", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetPageCountsResponse")]
        testing.Verivdp.returnType Info_GetPageCounts(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetPageCounts", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetPageCountsResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> Info_GetPageCountsAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/ConvertHTMLToPageflexXML", ReplyAction="http://tempuri.org/IVeriVDP/ConvertHTMLToPageflexXMLResponse")]
        testing.Verivdp.returnType ConvertHTMLToPageflexXML(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/ConvertHTMLToPageflexXML", ReplyAction="http://tempuri.org/IVeriVDP/ConvertHTMLToPageflexXMLResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> ConvertHTMLToPageflexXMLAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Build_VDPAsset", ReplyAction="http://tempuri.org/IVeriVDP/Build_VDPAssetResponse")]
        testing.Verivdp.returnType Build_VDPAsset(testing.Verivdp.requestType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Build_VDPAsset", ReplyAction="http://tempuri.org/IVeriVDP/Build_VDPAssetResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> Build_VDPAssetAsync(testing.Verivdp.requestType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit_Pageflex", ReplyAction="http://tempuri.org/IVeriVDP/Submit_PageflexResponse")]
        testing.Verivdp.returnType Submit_Pageflex(testing.Verivdp.requestTypeXmPie composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit_Pageflex", ReplyAction="http://tempuri.org/IVeriVDP/Submit_PageflexResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> Submit_PageflexAsync(testing.Verivdp.requestTypeXmPie composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetJobStatus", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetJobStatusResponse")]
        string Info_GetJobStatus(string transactionID, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetJobStatus", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetJobStatusResponse")]
        System.Threading.Tasks.Task<string> Info_GetJobStatusAsync(string transactionID, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetTaskLog", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetTaskLogResponse")]
        string Info_GetTaskLog(string transactionID, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Info_GetTaskLog", ReplyAction="http://tempuri.org/IVeriVDP/Info_GetTaskLogResponse")]
        System.Threading.Tasks.Task<string> Info_GetTaskLogAsync(string transactionID, string version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit_XMPie", ReplyAction="http://tempuri.org/IVeriVDP/Submit_XMPieResponse")]
        testing.Verivdp.returnType Submit_XMPie(testing.Verivdp.requestTypeXmPie composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit_XMPie", ReplyAction="http://tempuri.org/IVeriVDP/Submit_XMPieResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> Submit_XMPieAsync(testing.Verivdp.requestTypeXmPie composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit", ReplyAction="http://tempuri.org/IVeriVDP/SubmitResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, string>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(testing.Verivdp.returnType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(testing.Verivdp.requestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(testing.Verivdp.requestTypeXmPie))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(testing.Verivdp.requestTypeObject))]
        testing.Verivdp.returnType Submit(object composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVeriVDP/Submit", ReplyAction="http://tempuri.org/IVeriVDP/SubmitResponse")]
        System.Threading.Tasks.Task<testing.Verivdp.returnType> SubmitAsync(object composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVeriVDPChannel : testing.Verivdp.IVeriVDP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VeriVDPClient : System.ServiceModel.ClientBase<testing.Verivdp.IVeriVDP>, testing.Verivdp.IVeriVDP {
        
        public VeriVDPClient() {
        }
        
        public VeriVDPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VeriVDPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VeriVDPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VeriVDPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public testing.Verivdp.returnType Info_GetPageCounts(string value) {
            return base.Channel.Info_GetPageCounts(value);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> Info_GetPageCountsAsync(string value) {
            return base.Channel.Info_GetPageCountsAsync(value);
        }
        
        public testing.Verivdp.returnType ConvertHTMLToPageflexXML(string value) {
            return base.Channel.ConvertHTMLToPageflexXML(value);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> ConvertHTMLToPageflexXMLAsync(string value) {
            return base.Channel.ConvertHTMLToPageflexXMLAsync(value);
        }
        
        public testing.Verivdp.returnType Build_VDPAsset(testing.Verivdp.requestType composite) {
            return base.Channel.Build_VDPAsset(composite);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> Build_VDPAssetAsync(testing.Verivdp.requestType composite) {
            return base.Channel.Build_VDPAssetAsync(composite);
        }
        
        public testing.Verivdp.returnType Submit_Pageflex(testing.Verivdp.requestTypeXmPie composite) {
            return base.Channel.Submit_Pageflex(composite);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> Submit_PageflexAsync(testing.Verivdp.requestTypeXmPie composite) {
            return base.Channel.Submit_PageflexAsync(composite);
        }
        
        public string Info_GetJobStatus(string transactionID, string version) {
            return base.Channel.Info_GetJobStatus(transactionID, version);
        }
        
        public System.Threading.Tasks.Task<string> Info_GetJobStatusAsync(string transactionID, string version) {
            return base.Channel.Info_GetJobStatusAsync(transactionID, version);
        }
        
        public string Info_GetTaskLog(string transactionID, string version) {
            return base.Channel.Info_GetTaskLog(transactionID, version);
        }
        
        public System.Threading.Tasks.Task<string> Info_GetTaskLogAsync(string transactionID, string version) {
            return base.Channel.Info_GetTaskLogAsync(transactionID, version);
        }
        
        public testing.Verivdp.returnType Submit_XMPie(testing.Verivdp.requestTypeXmPie composite) {
            return base.Channel.Submit_XMPie(composite);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> Submit_XMPieAsync(testing.Verivdp.requestTypeXmPie composite) {
            return base.Channel.Submit_XMPieAsync(composite);
        }
        
        public testing.Verivdp.returnType Submit(object composite) {
            return base.Channel.Submit(composite);
        }
        
        public System.Threading.Tasks.Task<testing.Verivdp.returnType> SubmitAsync(object composite) {
            return base.Channel.SubmitAsync(composite);
        }
    }
}
